### ISSUE TITLE
I have an error when executing the commands on the Dashboard as Send Embed Message

### ISSUE THREAD

**Issue by loganou7** [dbm-network/extensions#26]
https://prnt.sc/saekys

TypeError: Discord.RichEmbed is not a constructor
at Object.run (/app/extensions/dbm_dashboard_EXT/actions/actions/send_embed_message.js:253:27)
at /app/extensions/dbm_dashboard_EXT/bin/dashboard.js:195:26
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
at Dashboard.checkAuth (/app/extensions/dbm_dashboard_EXT.js:323:12)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at next (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/layer.js:95:5)
    at /rbd/pnpm-volume/514a44c4-bd37-4eb7-aa41-8ee27101725b/node_modules/.registry.npmjs.org/express/4.17.1/node_modules/express/lib/router/index.js:281:22

**Comment by your-a-nerd** [comment]
Run `npm i discord.js@11.6.2` in your bots folder.
